version: 1
services:
  web:
    type: container
    build:
      dockerfile: Dockerfile
    ports:
      - 3000
    env:
      NODE_ENV: production
      DATABASE_URL: ${service.db.url}
      DB_SSL: "false"
    depends_on:
      - service: db
        condition: healthy
  db:
    type: postgres
    version: "17"
